## Linear Algebra Quiz #3

![title](./img/3_0.jpeg)

We strongly suggest working with numpy :)

In [2]:
#Do your imports here
import numpy as np

![title](./img/3_2.png)
Create a program that can output

- What is the value of element c23​ of Matrix C where C=A x B ?
- What is the value of element c23​ of Matrix C where C=B x A ?

In [11]:
def c_calc(m1,m2,i,j):
    m1 = np.array(m1)
    m2 = np.array(m2)
    if m1.shape[1] == m2.shape[0]:
        prod = np.dot(m1,m2)
        if i-1<=prod.shape[0] and j-1<=prod.shape[1]:
            return prod[i-1][j-1]
            #return prod
        else:
            return 'values i and j are out range matrix idices'
    else:
        return 'it s impossible multiply those two'
a = [[3,1,2],[-5,4,1],[0,3,-8]]
b=[[0,5,-1],[3,2,-1],[10,0.5,4]]
c_calc(a,b,2,3)

5.0

In [49]:
# okay numpy is great but... how would you inverse a matrix by hand?

def inverse_matrix(A):
    new = np.empty_like(A,dtype=float)#as we do some math calculation, we need both decimal and integer part of the element, and we store inside new matrix
    mat = np.array(A)
    for i in range(mat.shape[0]):
        for j in range(mat.shape[1]):
            a = np.delete(np.delete(mat,i,0),j,1) #creates submatrices
            new[i][j] = np.linalg.det(a)*(-1)**((i+1)+(j+1)) #construct cofactors matrix
            inverse = new.T/np.linalg.det(mat) # new.T is adjoint matrix of mat
    print(inverse)


a = [[3,1,2],[-5,4,1],[0,3,-8]]
inverse_matrix(a)




            

[[ 0.2        -0.08        0.04      ]
 [ 0.22857143  0.13714286  0.07428571]
 [ 0.08571429  0.05142857 -0.09714286]]


![title](./img/3_1.png)
Create a program that can output

- What is the value of the ijth element if i = 2 and j=3?
- What is the value of the ijth element if i = 3 and j=1?

In [13]:
# Just answer using code --> easy stuff!
def mat_solver(m1,m2,m3,i,j):
    m1 = np.array(m1)
    m2 = np.array(m2)
    m3 = np.array(m3)
    res = m1+m2-m3

    print('{},{} element of matrix is {}'.format(i,j,res[i-1,j-1]))
      
a = [[3,0.6,4,-3],[-1.3,4,0,8.6],[7,0,-8,0.006]]
b = [[3,-5.76,45,0],[2,-2,1.3,9],[-9,0,0,0]]
c = [[0,1009,-66.7849,90],[0,5,4,-0.07],[-7.7,0,0,0]]
i =2
j=3

mat_solver(a,b,c,i,j)

# Harder
# Can you build a matrix solver that can do output the result given n matrices and a sequence of operations such as [add subtract multiply transpose?]
#Some ideas on valid operations: Multiplication Addition Subtraction Inverstion Transposed. 

2,3 element of matrix is -2.7


![title](./img/3_3.png)
Create a program that can output
- How many rows will C have?
- How many columns will C have?
- What will be the value of c13​?

In [12]:
def c_calc(m1,m2,i,j):
    m1 = np.array(m1)
    m2 = np.array(m2)
    if m1.shape[1] == m2.shape[0]:
        prod = np.dot(m1,m2)
        print(prod)
        print('this matrix has {} rows and {} columns'.format(prod.shape[0],prod.shape[1]))
        if i-1<=prod.shape[0] and j-1<=prod.shape[1]:
            print('C{}{} element of matrix is {}'.format(i,j,prod[i-1,j-1]))
        else:
            return 'values i and j are out range matrix idices'
    else:
        return 'it s impossible multiply those two'
a = [[0.6,-15,2,5,98]]
b=[[2,2,-4],[9,-14,0],[13,-0.5,44],[1,9,4],[0,0,5]]
c_calc(a,b,1,3)

[[-102.8  255.2  595.6]]
this matrix has 1 rows and 3 columns
C13 element of matrix is 595.6
