# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow and in the numpy documentation. The goal of this collection is to offer a quick reference for both old and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel free to open an issue at <https://github.com/rougier/numpy-100>

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [8]:
print(np.__version__,)
np.show_config()

1.19.1
blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/saidalikhonalikhonov/opt/anaconda3/envs/sayeed/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/saidalikhonalikhonov/opt/anaconda3/envs/sayeed/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/saidalikhonalikhonov/opt/anaconda3/envs/sayeed/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/saidalikhonalikhonov/opt/anaconda3/envs/sayeed/include']
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/saidalikhonalikhonov/opt/anaconda3/envs/sayeed/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/saidalikhonalikhonov/opt/anaconda3/envs/sayeed/include']
lapack_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/saidalikhonalikhonov/opt/anaconda3/envs/sayeed/lib']


#### 3. Create a null vector of size 10 (★☆☆)

In [10]:
vector = np.zeros(10)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array (★☆☆)

In [13]:
def size_of_arr(arr):
    size_arr = arr.size
    item_size = arr.itemsize
    memory_size = size_arr * item_size
    return memory_size
print(size_of_arr(np.arange(5)))

40


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆)

In [15]:
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [17]:
null_vec = np.zeros(10)
null_vec[4] = 1

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆)

In [46]:
vec = np.arange(10,50)
print(vec)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last) (★☆☆)

In [47]:
vec = vec[::-1]
print(vec)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [51]:
mat = np.arange(9).reshape(( 3,3 ))
print(mat)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [58]:
arr = [1,2,0,0,4,0]
new = np.nonzero(arr)
print(new)

(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [60]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [61]:
np.random.random(size=(3,3,3))

array([[[7.19986812e-01, 8.65025080e-01, 7.47050817e-01],
        [5.20570013e-01, 8.92478636e-01, 7.61957084e-01],
        [4.84285456e-01, 8.45843381e-01, 4.11047827e-02]],

       [[5.09259590e-01, 2.30957585e-04, 7.05426966e-01],
        [5.62294002e-01, 6.91867644e-01, 6.14941090e-01],
        [2.41019810e-01, 7.28489052e-01, 8.48709060e-01]],

       [[8.20763212e-01, 6.44078616e-01, 9.48535521e-01],
        [5.00050808e-01, 5.01427062e-01, 5.51670106e-01],
        [9.73759979e-01, 5.19022855e-01, 2.10948386e-01]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [63]:
new = np.random.random(size=(10,10))
min = np.amin(new)
max = np.amax(new)
print(max,min)

0.9934619808633647 0.00454203389289598


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [66]:
new_vector = np.random.random(size=(30))
print(np.mean(new_vector))

0.5491676236614964


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [118]:
arr = np.ones((10,10))
arr[1:-1,1:-1] = 0
print(arr)
print(arr.shape)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
(10, 10)


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [76]:
def padding(arr):
    new = np.pad(arr,pad_width=1,mode='constant',constant_values=0)
    return new
print(padding(np.arange(9).reshape((3,3))))

[[0 0 0 0 0]
 [0 0 1 2 0]
 [0 3 4 5 0]
 [0 6 7 8 0]
 [0 0 0 0 0]]


#### 17. What is the result of the following expression? (★☆☆)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [77]:
print(0*np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [106]:
arr = 1+np.arange(4)
z = np.diag(arr,k=-1)
print(z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [116]:
arr = np.zeros((8,8))
arr[::2,::2] = 1
arr[1::2,1::2] = 1
print(arr)


[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [114]:
np.unravel_index(100,(6,7,8))


(1, 5, 4)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [125]:

array = np.array([[1,0],[0,1]])
tiled = np.tile(array,(4,4))
print(tiled)


[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [128]:
arr = np.random.random(size=(5,5))
print(arr)


[[0.86976222 0.52404825 0.20437098 0.15395893 0.88745252]
 [0.19740781 0.233308   0.4140454  0.81604967 0.6257481 ]
 [0.59361121 0.75062335 0.17643661 0.33179854 0.25760698]
 [0.85523806 0.21809711 0.17903788 0.64495026 0.78919144]
 [0.13737059 0.26704306 0.61505963 0.05564507 0.58238573]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [131]:
a = np.ones((5,3))
b=np.ones((3,2))
prod=np.dot(a,b)
print(prod)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [139]:
arr = np.arange(10)
new = arr[arr>=3]
new = new[new<8]
print(new)

[3 4 5 6 7]


#### 26. What is the output of the following script? (★☆☆)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [2]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [4]:
import numpy as np
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

/var/folders/1h/x7tmv9xd1bsclx868ql32nf40000gn/T/ipykernel_70351/291608809.py:2: RuntimeWarning: invalid value encountered in true_divide
  np.array(0) / np.array(0)
/var/folders/1h/x7tmv9xd1bsclx868ql32nf40000gn/T/ipykernel_70351/291608809.py:3: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)


array([-9.22337204e+18])

#### 29. How to round away from zero a float array ? (★☆☆)

In [9]:
arr = np.array([1.5,5.5,3.5])
print(arr.round())

[2. 6. 4.]


#### 30. How to find common values between two arrays? (★☆☆)

In [14]:
def check_arr(c1,c2):
    return np.intersect1d(c1,c2)

check_arr([1,4,3,5,6],[1,4,67,78])

array([1, 4])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [ ]:
#np.seterr(all='ignore') #it also canbe , warn raise etc.

#### 32. Is the following expressions true? (★☆☆)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
# nan is not equal to complex number

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [18]:
today = np.datetime64('today','D')
yesterday = today - np.timedelta64(1,'D')
tomorrow = today + np.timedelta64(1,'D')


2021-09-24


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [13]:
arr = np.arange("2016-07","2016-08",dtype="datetime64[D]")
print(arr)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆)

In [25]:
def func(A,B):
    return np.multiply(np.add(A,B),np.negative(A/2))

func(np.array([1,2]),np.array([4,2]))

array([-2.5, -4. ])

#### 36. Extract the integer part of a random array using 5 different methods (★★☆)

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [22]:
arr = np.zeros((5,5))
arr[:,:] = np.arange(5)
print(arr)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [32]:
def generatorr(n):
    return np.random.randint(20,size=n)
generatorr(10)

array([ 1, 17, 18, 10,  5, 13,  6,  7, 13,  5])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [42]:
arr = np.linspace(0,1,num=11,endpoint=False)
print(arr)
arr[arr>0]

[0.         0.09090909 0.18181818 0.27272727 0.36363636 0.45454545
 0.54545455 0.63636364 0.72727273 0.81818182 0.90909091]


array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [45]:
arr = np.random.randint(10,size=10)
print(np.sort(arr))

[0 3 3 4 4 6 6 8 8 8]


#### 41. How to sum a small array faster than np.sum? (★★☆)

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [47]:
arr1 = np.random.randint(10,size=4)
arr2 = np.random.randint(10,size=4)
arr1 == arr2

np.array_equal(arr1,arr2)

False

#### 43. Make an array immutable (read-only) (★★☆)

In [49]:
arr = np.array([1,3,4,5])
arr.flags.writeable = False

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [57]:
z = np.random.randint(2,size=20).reshape((10,2))
x,y = z[:,0], z[:,1]
radi = np.sqrt( x**2 + y**2 )
angl = np.arctan2(y,x)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [63]:
a = np.random.randint(5,size=10) #array with random numbers will be created 
np.where(a==np.amax(a),0,a) #it takes the condition first, action if condtion True is second, the last if condition False

array([1, 2, 3, 3, 0, 2, 0, 3, 0, 0])

#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆)

####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

In [ ]:
#we actually print all values whith print function
#using set_printoptions can adjust the way obects get printed

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [9]:
import numpy as np
def find_closest(arr, val):
    new_arr = (arr - val)
    new_arr = np.abs(new_arr)
    i = np.argmin(new_arr)
    return arr[i]

find_closest(np.array([1,2,3,4,5,85,70]),4)

4

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [34]:
arr = np.arange(200).reshape((100,2))
x,y = np.atleast_2d(arr[:,0],arr[:,1]) #separating x and y from the conrdinates of point
delta_x = x - x.T # calculating all the delta x
delta_y = y - y.T #calculatin all the delta y

d = np.sqrt(delta_x**2 + delta_y**2) #each row stores the array of distances from that particular point to each point in the array
print(d)




[[  0.           2.82842712   5.65685425 ... 274.3574311  277.18585823
  280.01428535]
 [  2.82842712   0.           2.82842712 ... 271.52900398 274.3574311
  277.18585823]
 [  5.65685425   2.82842712   0.         ... 268.70057685 271.52900398
  274.3574311 ]
 ...
 [274.3574311  271.52900398 268.70057685 ...   0.           2.82842712
    5.65685425]
 [277.18585823 274.3574311  271.52900398 ...   2.82842712   0.
    2.82842712]
 [280.01428535 277.18585823 274.3574311  ...   5.65685425   2.82842712
    0.        ]]


#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [44]:
a = np.arange(5, dtype='float32')
a.astype("float32",copy=False)

array([0., 1., 2., 3., 4.], dtype=float32)

#### 54. How to read the following file? (★★☆)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [ ]:
#open the file
#f = open(file.txt)
#f.read()
#data = np.genfromtxt(f,delimiter=",")

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [45]:
import numpy as np
a = np.arange(9).reshape( (3,3) )
for i,value in np.ndenumerate(a):
    print(i,value)

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [ ]:
a = np.zeros((8,8))

#### 58. Subtract the mean of each row of a matrix (★★☆)

In [26]:
a = np.arange(10).reshape((5,2))
a = a - np.mean(a,axis=1,keepdims=True)
a


array([[-0.5,  0.5],
       [-0.5,  0.5],
       [-0.5,  0.5],
       [-0.5,  0.5],
       [-0.5,  0.5]])

#### 59. How to sort an array by the nth column? (★★☆)

In [51]:
def sort_arr(arr,n):
    ind = np.argsort(arr[:,n])
    return arr[ind]

a = np.array([[2,5,6],[5,4,6],[1,3,5]])
print(a)
sort_arr(a,1)

[[2 5 6]
 [5 4 6]
 [1 3 5]]


array([[1, 3, 5],
       [5, 4, 6],
       [2, 5, 6]])

#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [17]:

Z = np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())

True
[[1 0 2 0 0 1 2 0 2 2]
 [2 1 1 0 2 1 1 1 2 2]
 [0 0 2 2 0 2 0 2 1 1]]


#### 61. Find the nearest value from a given value in an array (★★☆)

In [2]:
import numpy as np
def find_closest(arr, val):
    new_arr = (arr - val)
    new_arr = np.abs(new_arr)
    i = np.argmin(new_arr)
    return arr[i]

find_closest(np.array([1,2,3,4,5,85,70]),4)

4

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [11]:
arr = np.array([1,3,4,1,2])
arr_2 = np.zeros(12)
for i in arr:
    arr_2[i]+=1

print(arr_2)


[0. 2. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [20]:
X = np.arange(10)
lis = [1,3,5,6,2,4,9,0,8,11]
new = np.zeros(20)
count = 0
for i in X:
    j = lis[count]
    new[j] = i
    count+=1
new

array([7., 0., 4., 1., 5., 2., 3., 0., 8., 6., 0., 9., 0., 0., 0., 0., 0.,
       0., 0., 0.])

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [24]:
a = np.arange(24).reshape((2,3,2,2))
print(np.sum(a,axis=(-2,-1)))

[[ 6 22 38]
 [54 70 86]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [43]:
S = np.random.randint(0,20,20)
D = np.arange(20)

print(S)
print(D)

for i in S:
    res = np.sum(D[:i])/len(D[:i])
    print(res)





[ 8 14 15  7 16 11  0  0 19  9 18  3  2 11 14  1 10 15 16  1]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
3.5
6.5
7.0
3.0
7.5
5.0
nan
nan
9.0
4.0
8.5
1.0
0.5
5.0
6.5
0.0
4.5
7.0
7.5
0.0


/var/folders/1h/x7tmv9xd1bsclx868ql32nf40000gn/T/ipykernel_6759/2726878399.py:8: RuntimeWarning: invalid value encountered in long_scalars
  res = np.sum(D[:i])/len(D[:i])


#### 69. How to get the diagonal of a dot product? (★★★)

In [66]:
def diagonals(A,B):
   return np.diag(np.dot(A,B))

diagonals(np.arange(9).reshape((3,3)),np.arange(9).reshape((3,3)))

array([ 15,  54, 111])

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [119]:
a = np.arange(1,6)
b = np.zeros((17))
b[::4] = a #takes every 4 element and change it item from a
print(b)


[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

In [85]:
a = np.arange(9).reshape((3,3))
#we can do like this
a[[0,2]], a[[2,0]] = a[[2,0]],a[[0,2]]#swaps 0 and 2 nd rows, it s shorter for [[0,2],:]

print(a)

[[6 7 8]
 [3 4 5]
 [0 1 2]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

array([0, 2, 1, 4, 1, 1, 1, 0, 0, 1])

#### 75. How to compute averages using a sliding window over an array? (★★★)

In [53]:
def moving_average(a, n=3) :
    res = np.cumsum(a)
    res[n:] = res[n:] - res[:-n]
    return res[n-1:]/n
arr = np.arange(20)
moving_average(arr)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18.])

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★)

In [6]:
import numpy as np
def matrix_builder(a,window=3):
    new = np.zeros((len(a)-2,3))
    for i in range((len(a))-2):
        new[i,:] = a[i:i+3]
    print(new)
matrix_builder(np.arange(20))

c = np.array([[2,2],[3,3]])




[[ 0.  1.  2.]
 [ 1.  2.  3.]
 [ 2.  3.  4.]
 [ 3.  4.  5.]
 [ 4.  5.  6.]
 [ 5.  6.  7.]
 [ 6.  7.  8.]
 [ 7.  8.  9.]
 [ 8.  9. 10.]
 [ 9. 10. 11.]
 [10. 11. 12.]
 [11. 12. 13.]
 [12. 13. 14.]
 [13. 14. 15.]
 [14. 15. 16.]
 [15. 16. 17.]
 [16. 17. 18.]
 [17. 18. 19.]]


2

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [79]:
Z = np.random.uniform(1,10,100)
np.negative(Z)


array([-7.7468703 , -1.82034918, -6.1325081 , -4.98042127, -3.8251988 ,
       -5.82268648, -2.55571392, -1.38680655, -8.50982064, -4.14706399,
       -3.74801015, -5.65962421, -4.14334442, -9.18225402, -5.12023026,
       -9.2044395 , -9.35269762, -1.28601845, -9.53452574, -8.4986363 ,
       -1.46780908, -4.19139803, -7.17061787, -9.68287059, -1.79543325,
       -8.16611811, -4.75863952, -3.78984095, -7.21783336, -7.67809166,
       -3.73622068, -1.00619533, -7.11895224, -9.38523788, -7.15154563,
       -5.51775398, -6.60414443, -5.34071812, -7.40550034, -4.3836496 ,
       -8.53147134, -7.60444503, -2.27455953, -6.73922523, -4.44488061,
       -6.05843713, -8.11822637, -1.03494055, -7.82217338, -5.3780494 ,
       -8.48800113, -7.08941309, -6.78683174, -5.78691195, -7.90887359,
       -7.18550418, -6.9603569 , -8.14083941, -8.02772645, -7.57953007,
       -8.63933994, -5.40698208, -8.3165204 , -1.78033974, -7.31938183,
       -3.62967382, -7.84138056, -6.33046902, -5.3561226 , -7.08

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

In [77]:
import numpy as np
P0  = np.array([[0,1],[2,3],[4,1],[3,3]])
P1  = np.array([[2,5],[4,4],[0,0],[2,8]])
point = np.array([2,0])

def distance(P0,P1,point):
        deltas = (P0 - P1) #finds delta x and delta y
        k = (deltas[:,1]/deltas[:,0])# using delta x and delta y stores slope of the line 
        b = P0[:,1] - k * P0[:,0] # stores constant member of line equation
        distance = (abs(k*point[0]-point[1]+b))/np.sqrt(k**2+1) # equation for distance 
        distance = distance.reshape((len(P0),1)) # reshapes list of results into n x 1 2d matrix, vertical matrix
        return distance
     

distance(P0,P1,point)





array([[2.23606798],
       [2.68328157],
       [0.48507125],
       [1.56892908]])

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

In [80]:
points = [[2,0],[1,0],[3,4]]
distance_points = np.array([distance(P0,P1,point) for point in points]) # using for loop we can iterate over set points
distance_points



array([[[2.23606798],
        [2.68328157],
        [0.48507125],
        [1.56892908]],

       [[1.34164079],
        [2.23606798],
        [0.24253563],
        [2.54950976]],

       [[1.34164079],
        [0.4472136 ],
        [3.15296313],
        [0.19611614]]])

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

In [169]:
Z = np.random.randint(0,10,(10,10))
shape = (7,7)
position = (1,1)

R = np.zeros(shape)
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)







[[5 5 1 1 5 4 1 0 6 3]
 [6 1 8 0 2 7 4 6 0 5]
 [9 5 0 5 4 3 5 5 6 8]
 [7 4 2 1 0 6 2 2 5 1]
 [6 8 1 2 1 7 8 6 2 4]
 [2 0 1 8 5 6 5 0 7 1]
 [0 9 6 1 0 1 9 1 5 0]
 [5 9 2 3 4 3 7 7 2 1]
 [1 2 5 2 3 7 2 9 5 8]
 [3 4 0 0 0 2 4 1 9 3]]
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 5. 5. 1. 1. 5.]
 [0. 0. 6. 1. 8. 0. 2.]
 [0. 0. 9. 5. 0. 5. 4.]
 [0. 0. 7. 4. 2. 1. 0.]
 [0. 0. 6. 8. 1. 2. 1.]]


/var/folders/1h/x7tmv9xd1bsclx868ql32nf40000gn/T/ipykernel_21586/2727336794.py:22: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  R[r] = Z[z]


#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★)

In [176]:
Z = np.arange(15)
R = np.zeros((len(Z)-3,4))
for i in range(len(Z)-3):
    R[i,:] = Z[i:i+4]


[[ 0.  1.  2.  3.]
 [ 1.  2.  3.  4.]
 [ 2.  3.  4.  5.]
 [ 3.  4.  5.  6.]
 [ 4.  5.  6.  7.]
 [ 5.  6.  7.  8.]
 [ 6.  7.  8.  9.]
 [ 7.  8.  9. 10.]
 [ 8.  9. 10. 11.]
 [ 9. 10. 11. 12.]
 [10. 11. 12. 13.]
 [11. 12. 13. 14.]]


#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

In [216]:
mat = np.random.randint(0,25,50)

np.bincount(mat).argmax() 
#bincount returns occurences of bin values, argmax returns index of the max value(index of the occurence is equal to the value)

3

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [237]:
mat = np.random.randint(0,20,(10,10))

print(mat)

print("-"*30)
for i in range((mat.shape[0])-2):
    for j in range(mat.shape[1]-2):
        print(mat[i:i+3,j:j+3])

[[ 2 13  3  4 17 15 18  4 11  2]
 [11 18 18  0 14 11  6 15 11  6]
 [16 17 18  0 19 17  2 14  2 19]
 [16 18  4  3  2 16 10 13  7 17]
 [16  7  8  8  3 13  4 12 16 10]
 [15  1 14  9  2 11  2  3  3  3]
 [ 0 19  9  4 17 11  5 15  2  2]
 [15  3 19  1 16  1  1 16  0 17]
 [ 2 16  4  5 13  2  4  7 14  0]
 [ 2  8  9  5 14 13 14 19  7 18]]
------------------------------
[[ 2 13  3]
 [11 18 18]
 [16 17 18]]
[[13  3  4]
 [18 18  0]
 [17 18  0]]
[[ 3  4 17]
 [18  0 14]
 [18  0 19]]
[[ 4 17 15]
 [ 0 14 11]
 [ 0 19 17]]
[[17 15 18]
 [14 11  6]
 [19 17  2]]
[[15 18  4]
 [11  6 15]
 [17  2 14]]
[[18  4 11]
 [ 6 15 11]
 [ 2 14  2]]
[[ 4 11  2]
 [15 11  6]
 [14  2 19]]
[[11 18 18]
 [16 17 18]
 [16 18  4]]
[[18 18  0]
 [17 18  0]
 [18  4  3]]
[[18  0 14]
 [18  0 19]
 [ 4  3  2]]
[[ 0 14 11]
 [ 0 19 17]
 [ 3  2 16]]
[[14 11  6]
 [19 17  2]
 [ 2 16 10]]
[[11  6 15]
 [17  2 14]
 [16 10 13]]
[[ 6 15 11]
 [ 2 14  2]
 [10 13  7]]
[[15 11  6]
 [14  2 19]
 [13  7 17]]
[[16 17 18]
 [16 18  4]
 [16  7  8]]
[[17 18  

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★)

[[ 2  9 17 12  4]
 [ 9  5 17 12  5]
 [17 17  5 42  7]
 [12 12 42  1  8]
 [ 4  5  7  8  6]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [248]:
mat = np.random.randint(0,25,(16,16))
#mat = np.ones(256).reshape((16,16))
print(mat)
for i in range(mat.shape[0]-3):
    for j in range(mat.shape[1]-3):
        print(np.sum(mat[i:i+4,j:j+4]))



[[24 13 22 11 10 11  9 23  0  7 13  5  7 15 24 18]
 [ 4 22  4 11 22  3  2  0 24  9 16 22 10 12 10  2]
 [14 14 13  5  6 24 13  1  5 11 18 15  2  7 10 18]
 [ 9  6 20  8 18 23  8 24 19  3 20 14 15  0 10 18]
 [23 22 18 13  8 14  2 14 17  0 24 13 14  1 23 11]
 [ 4  2 19  9 24  2 15  7 20 16  8 13 23 10  2  7]
 [13 13 16  7  3  1 16 13  2 22  5 13 23  4 23  3]
 [17  8  9 14  8 22 17 16 11  2  1  5  9  1  5 11]
 [ 5  2 13  3 24  8  8 12 11 17 16 19 16 14 22  4]
 [10 23  0  9 12 17 16 17  6 19  4 16 16 20  8 22]
 [18  5 20 16 15 17 23  8 12  6  8 18 12 22  6  1]
 [23  9 21  9 21  5 22 15 24 18  7  8  1 13 16 13]
 [ 5 24 13 19 19 10  9  6  7  9  8  2  9  7  4  6]
 [ 3  7 15  0 16 12 15 15  1 13 16 20 16  4 18  1]
 [10 19 10 17 12 21 23 22  6  8 24 24  6  5 18 20]
 [ 0 13  3  3  3  1  4 16 14  1 13 13  7 15 24  3]]
200
205
211
184
197
189
158
193
201
187
191
178
178
206
210
210
180
182
193
152
205
230
206
203
178
163
199
205
224
192
203
208
175
207
216
209
197
172
171
202
206
203
171
192
197
198

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

In [331]:
new = np.arange(25).reshape((5,5))
np.random.shuffle(new)
def n_largest(arr,n):
    arr = arr.flatten()
    arr.sort()
    print(arr[-n:])
print(new)
n_largest(new,5)



[[ 5  6  7  8  9]
 [20 21 22 23 24]
 [ 0  1  2  3  4]
 [15 16 17 18 19]
 [10 11 12 13 14]]
[20 21 22 23 24]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

(20,)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [187]:
arr = np.arange(10).reshape( (5,2) )

np.unique(arr,axis=0)


array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)